# Base colors
WHITE = "#FFFFFF"
BLACK = "#333333"
GRAY_1 = "#f0e7dd"
GRAY_2 = "#F3F4F4"

ROSEWOOD = "#9d0208"
SINOPIA = "#CA6702"
ORANGE = "#f48c06"
YELLOW = "#ffba08"

# Main theme colors
PRIMARY = ORANGE
SECONDARY = YELLOW

SUCCESS = "#3BB273"
INFO = "#3A59D1"
WARNING = "#FFBE0B"
DANGER = "#E5383B"

# App
APP_BACKGROUND = GRAY_2

# Basic variables
BORDER_COLOR = "#e0d7cd"

# Navbar
NAVBAR_BACKGROUND = SINOPIA

# Card
CARD_HEADER = GRAY_1
CARD_BACKGROUND = WHITE
CARD_BACKGROUND_OPACITY = "rgba(255, 255, 255, 0.94)"

# Plots
PLOT_BACKGROUND_COLOR = WHITE
COLOR_CONTINUOUS_SCALE = "peach"

# Text colors
TEXT_PRIMARY = BLACK
TEXT_SECONDARY = WHITE

# Gender specific colors
MALE_COLOR = "#4895EF"
FEMALE_COLOR = "#F72585"
UNKNOWN_GENDER_COLOR = "#B5838D"
